# Generated by Django 5.1.2 on 2024-10-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('dead_line', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('check_box', models.BooleanField(default=False)),
            ],
        ),
    ]
