# Generated by Django 5.1.2 on 2024-10-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dead_line',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
