# Generated by Django 5.1.2 on 2024-10-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_task_dead_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dead_line',
            new_name='deadline',
        ),
    ]
